### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by gaul** [dgraziotin/mbpfan#160]
master includes kernel < 3.15 support and several small optimizations.  Commits since 2.0.2: https://github.com/dgraziotin/mbpfan/compare/v2.0.2...master

TODOs:

- [x] merge one of the RPM PRs: #154, #157 
- [x] merge or close fan max speed detection #137 
- [x] try to resolve open issues, especially https://github.com/dgraziotin/mbpfan/issues/155#issuecomment-414484540

Propose releasing 2.1.0 next week.  I would appreciate if users could test against master and report success and failures here since behaviors differ based on kernel and hardware.  Thanks!

**Comment by gaul** [comment]
> @gaul please add yourself to AUTHORS

Done in d717ffb220a96a56359433c6db41a01180e21102.

**Comment by gaul** [comment]
Done.
